{{- if .Values.auth.license.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.license.secretName }}
  labels:
    {{- include "blinkidVerify.labels" . | nindent 4 }}
stringData:
  LICENSE_KEY: {{ .Values.auth.license.licenseKey | required "auth.license.licenseKey is required when auth.license.createSecret is true" | quote }}
  LICENSE_APPLICATION_ID: {{ .Values.auth.license.applicationId | required "auth.license.applicationId is required when auth.license.createSecret is true" | quote }}
type: Opaque
{{- end }}
