{{- if and .Values.blinkIdVerify.enabled .Values.blinkIdVerify.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "blinkidVerify.fullname" . }}
  labels:
    {{- include "blinkidVerify.labels" . | nindent 4 }}
  {{- with .Values.blinkIdVerify.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.blinkIdVerify.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.blinkIdVerify.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.blinkIdVerify.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            pathType: {{ $.Values.blinkIdVerify.ingress.pathType }}
            backend:
              service:
                name: {{ include "blinkidVerify.fullname" $ }}
                port:
                  number: {{ $.Values.blinkIdVerify.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
